'use strict';
/* gen_vfx_schema.mjs — data/vfx-schema.json ko single source maan kar do artifacts
 * banata hai:
 *   - src/vfx/schema.generated.ts    (Remotion render-time, validate.ts consume)
 *   - dashboard/vfx-schema.generated.cjs (server sanitize, custom-vfx.js consume)
 * Drift-guard: contract checks neeche — schema ghalat ho to exit(1) fail-loud,
 * taake ghalat table silently generate na ho. No eval / no dynamic constructors.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC_JSON = resolve(ROOT, '..', 'data', 'vfx-schema.json');
const OUT_TS = resolve(ROOT, 'src', 'vfx', 'schema.generated.ts');
const OUT_CJS = resolve(ROOT, 'dashboard', 'vfx-schema.generated.cjs');

const EXPECTED_FIELDS = [
  'tileSize', 'strokeWidth', 'alpha', 'opacity', 'bandSize',
  'breathFrames', 'breathAmpl', 'seedSalt',
];
const EXPECTED_ENUMS = ['kind', 'colorToken', 'zones'];
const INT_FIELDS = new Set(['tileSize', 'bandSize', 'breathFrames', 'seedSalt']);
const EXPECTED_OVERRIDES = [
  'cornerInset', 'cornerSize', 'cornerOpacity', 'frameEnabled', 'frameOpacity1',
  'frameOpacity2', 'ornamentScale', 'ornamentSwayDeg', 'raysOpacity',
  'orbsOpacity', 'particlesScale', 'grainOpacityDark', 'grainOpacityPaper',
  'vignetteScale', 'bokehCount', 'bokehOpacity', 'chromaticAberration',
  'shimmerStrength', 'noiseVeilOpacity', 'raysAngleDeg',
];

function fail(msg) {
  console.error('SCHEMA ERROR: ' + msg);
  process.exit(1);
}
const isFin = (v) => typeof v === 'number' && Number.isFinite(v);

let schema;
try {
  schema = JSON.parse(readFileSync(SRC_JSON, 'utf8'));
} catch (e) {
  fail('cannot read ' + SRC_JSON + ': ' + e.message);
}

// ── contract checks (drift-guard) ──
if (schema.schemaVersion !== 1) fail('schemaVersion must be 1');
if (typeof schema.hexColorPattern !== 'string' || !schema.hexColorPattern.length) {
  fail('hexColorPattern missing');
}
const pat = schema.pattern;
if (!pat || !pat.fields || !pat.enums) fail('pattern.fields / pattern.enums required');
for (const k of EXPECTED_FIELDS) {
  const f = pat.fields[k];
  if (!f || !isFin(f.min) || !isFin(f.max) || !isFin(f.def)) {
    fail('pattern field "' + k + '" needs numeric min/max/def');
  }
  if (f.min > f.def || f.def > f.max) fail('pattern field "' + k + '" violates min<=def<=max');
  if (INT_FIELDS.has(k) && f.type !== 'int') fail('pattern field "' + k + '" must be type int');
}
for (const k of EXPECTED_ENUMS) {
  const e = pat.enums[k];
  if (!Array.isArray(e) || !e.length || e.some((v) => typeof v !== 'string')) {
    fail('enum "' + k + '" must be a non-empty string array');
  }
}
if (
  !Array.isArray(pat.zonesExclusive) ||
  pat.zonesExclusive.some((v) => !pat.enums.zones.includes(v))
) {
  fail('zonesExclusive must be a subset of the zones enum');
}
const ov = Array.isArray(schema.overrides) ? schema.overrides : null;
if (!ov || ov.length !== EXPECTED_OVERRIDES.length) {
  fail('overrides count != ' + EXPECTED_OVERRIDES.length);
}
const ovKeys = ov.map((x) => x.key);
if (EXPECTED_OVERRIDES.some((k) => !ovKeys.includes(k))) fail('overrides missing expected keys (drift)');
let numOv = 0;
let boolOv = 0;
for (const o of ov) {
  if (typeof o.key !== 'string' || !o.key.length) fail('override key required');
  if (o.type === 'boolean') {
    boolOv++;
    if (o.min !== undefined) fail('boolean override "' + o.key + '" cannot carry min/max/def');
  } else if (o.type === 'number') {
    numOv++;
    if (!isFin(o.min) || !isFin(o.max) || !isFin(o.def)) {
      fail('numeric override "' + o.key + '" needs numeric min/max/def');
    }
    if (o.min > o.def || o.def > o.max) fail('override "' + o.key + '" violates min<=def<=max');
  } else {
    fail('override "' + o.key + '" type must be number | boolean');
  }
}
if (numOv !== 19 || boolOv !== 1) fail('expected exactly 19 numeric + 1 boolean override');

// ── render (string-template composition, no eval) ──
const ts = [
  '// AUTO-GENERATED by scripts/gen_vfx_schema.mjs — DO NOT EDIT. Edit data/vfx-schema.json.',
  '// Single source of truth for VFX numeric limits, enums and the override whitelist.',
  '// Consumers: src/vfx/validate.ts (render-time fail-loud).',
  '',
  'export interface VfxNumBound {',
  "  type: 'int' | 'float';",
  '  min: number;',
  '  max: number;',
  '  def: number;',
  '}',
  '',
  'export interface VfxEnumSet {',
  '  [k: string]: readonly string[];',
  '}',
  '',
  'export interface VfxOverrideCfg {',
  '  key: string;',
  "  type: 'number' | 'boolean';",
  '  min?: number;',
  '  max?: number;',
  '  def?: number;',
  '}',
  '',
  'export const VFX_SCHEMA = ' + JSON.stringify(schema, null, 2) + ' as const;',
  '',
].join('\n');
writeFileSync(OUT_TS, ts, 'utf8');

const deepFreeze = (v) => {
  if (v && typeof v === 'object') {
    for (const k of Object.keys(v)) deepFreeze(v[k]);
    Object.freeze(v);
  }
  return v;
};
const cjs = [
  "'use strict';",
  '// AUTO-GENERATED by scripts/gen_vfx_schema.mjs — DO NOT EDIT. Edit data/vfx-schema.json.',
  '// Server-side twin of src/vfx/schema.generated.ts — dashboard sanitizer isi ko consume karta hai.',
  '',
  'module.exports = ' + JSON.stringify(deepFreeze(JSON.parse(JSON.stringify(schema)))) + ';',
  '',
].join('\n');
writeFileSync(OUT_CJS, cjs, 'utf8');

console.log('gen:vfx-schema OK');
console.log('  schema ' + SRC_JSON);
console.log('  ts     ' + OUT_TS + '  (' + EXPECTED_FIELDS.length + ' pattern fields, ' + ov.length + ' overrides)');
console.log('  cjs    ' + OUT_CJS);